# Generated by Django 4.2.25 on 2025-11-05 06:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_departments'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('BackupHistoryID', models.UUIDField(db_column='BackupHistoryID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('log_file', models.FileField(blank=True, null=True, upload_to='logs/')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to='backups/')),
            ],
            options={
                'db_table': 'BackupHistory',
            },
        ),
        migrations.CreateModel(
            name='BackupSchedule',
            fields=[
                ('BackupSchedule', models.UUIDField(db_column='BackupScheduleID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('time', models.TimeField()),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('backup_size', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'BackupSchedule',
            },
        ),
    ]
