# Generated by Django 4.2.25 on 2025-11-05 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_backuphistory_backupschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backupschedule',
            old_name='BackupSchedule',
            new_name='BackupScheduleID',
        ),
    ]
