# Generated by Django 4.2.25 on 2025-11-06 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_backupschedule_backupschedule_backupscheduleid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupSchedule',
        ),
    ]
