# Generated by Django 4.2.25 on 2025-11-06 05:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_delete_backupschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='in_progress', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.backuphistory')),
            ],
            options={
                'db_table': 'RestoreOperation',
            },
        ),
    ]
