# Generated by Django 4.2.25 on 2025-11-07 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_restoreoperation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backuphistory',
            old_name='backup_file',
            new_name='BackupFile',
        ),
        migrations.RenameField(
            model_name='backuphistory',
            old_name='log_file',
            new_name='BackupLogFile',
        ),
        migrations.RenameField(
            model_name='backuphistory',
            old_name='name',
            new_name='BackupName',
        ),
        migrations.RenameField(
            model_name='backuphistory',
            old_name='size',
            new_name='BackupSize',
        ),
        migrations.RenameField(
            model_name='backuphistory',
            old_name='status',
            new_name='BackupStatus',
        ),
        migrations.RenameField(
            model_name='backuphistory',
            old_name='timestamp',
            new_name='BackupTimestamp',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='backup',
            new_name='BackupHistoryID',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='completed_at',
            new_name='RestoreCompletedAt',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='id',
            new_name='RestoreID',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='message',
            new_name='RestoreMessage',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='progress',
            new_name='RestoreProgress',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='started_at',
            new_name='RestoreStartedAt',
        ),
        migrations.RenameField(
            model_name='restoreoperation',
            old_name='status',
            new_name='RestoreStatus',
        ),
    ]
