# Generated by Django 4.2.25 on 2025-11-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_rename_backup_file_backuphistory_backupfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restoreoperation',
            name='BackupHistoryID',
            field=models.ForeignKey(db_column='BackupHistoryID', on_delete=django.db.models.deletion.CASCADE, to='events.backuphistory'),
        ),
    ]
