# Generated by Django 5.2.7 on 2025-10-10 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArcasysApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='UserCreateAt',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isActive',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isAdmin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isStaff',
        ),
        migrations.AddField(
            model_name='user',
            name='UserApprovedAt',
            field=models.DateTimeField(blank=True, db_column='UserApprovedAt', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='UserApprovedBy',
            field=models.ForeignKey(blank=True, db_column='UserApprovedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='UserCreatedAt',
            field=models.DateTimeField(db_column='UserCreatedAt', default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='isUserActive',
            field=models.BooleanField(db_column='isUserActive', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isUserAdmin',
            field=models.BooleanField(db_column='isUserAdmin', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='isUserStaff',
            field=models.BooleanField(db_column='isUserStaff', default=False),
        ),
    ]
