# Generated by Django 5.2.7 on 2025-10-14 20:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.UUIDField(db_column='RoleID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('RoleName', models.CharField(db_column='RoleName', max_length=50, unique=True)),
                ('RoleDescription', models.TextField(blank=True, db_column='RoleDescription')),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.UUIDField(db_column='UserID', default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UserFullName', models.CharField(db_column='UserFullName', max_length=255)),
                ('UserEmail', models.EmailField(db_column='UserEmail', max_length=254, unique=True)),
                ('UserPasswordHash', models.CharField(blank=True, db_column='UserPasswordHash', max_length=128)),
                ('UserCreatedAt', models.DateTimeField(db_column='UserCreatedAt', default=django.utils.timezone.now)),
                ('UserLastLogin', models.DateTimeField(blank=True, db_column='UserLastLogin', null=True)),
                ('isUserActive', models.BooleanField(db_column='isUserActive', default=False)),
                ('UserApprovedAt', models.DateTimeField(blank=True, db_column='UserApprovedAt', null=True)),
                ('isUserAdmin', models.BooleanField(db_column='isUserAdmin', default=False)),
                ('isUserStaff', models.BooleanField(db_column='isUserStaff', default=False)),
                ('UserApprovedBy', models.ForeignKey(blank=True, db_column='UserApprovedBy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('RoleID', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, to='users.role')),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
